apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/blues-yang/GitOps
    targetRevision: HEAD
    path: hello/chart
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true