apiVersion: v1
kind: Service
metadata:
  name: symphony-service-ext
spec:
  selector:
    app: symphony-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 8088
    targetPort: 8088
    name: https