apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webmodule
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/blues-yang/GitOps
    targetRevision: HEAD
    path: voe/chart
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true